### ISSUE TITLE
UTF-8

### ISSUE THREAD

**Issue by ivinkaf** [Hiswe/mosaico-backend#49]
Hi,

when I use in Text block special characters as "šážť", in html code there are displayed with HTML name, such as: "<p>Toto &scaron;pe&ccaron;&iacute;&aacute;lne charaktery &zcaron;eb&yacute; &aacute;&scaron;&ccaron; ne&iacute;&ccaron;vieme</p>"

is there, please, a way to use in html code symbols "á" instead of html name for special characters?

Thanks
Ivet

**Comment by Hiswe** [comment]
Not sure to totally understand.
Are the characters replaced by [html entities?](https://en.wikipedia.org/wiki/List_of_XML_and_HTML_character_entity_references)

If so, I guess it's done by the [tiny mce editor](https://www.tiny.cloud/)

**Comment by ivinkaf** [comment]
Yes, if I write á in code it is replaced by &aacute;  https://www.starr.net/is/type/htmlcodes.html

Do you have any idea how to change it?
Thanks

**Comment by Hiswe** [comment]
No idea :/ 
and not sure it's a desires behavior.
This editor targets email client, so I think having HTML entities is better for compatibility.

Do you have any display problems?

**Comment by Hiswe** [comment]
@ivinkaf can you try on the [original mosaico editor](https://mosaico.io/) if you have the same output?

**Comment by ivinkaf** [comment]
Thanks, I tried original mosaico editor and it is working there...the output is á...

**Comment by Hiswe** [comment]
So this should come from the [server/download.js](https://github.com/goodenough/mosaico-backend/blob/master/server/download.js)

the [secureHtml function](https://github.com/goodenough/mosaico-backend/blob/master/server/download.js#L25-L34) does that.

You could replace it like this:

```js
function secureHtml(html) {
  return html
}
```

**Comment by ivinkaf** [comment]
Thanks! I have replaced it, and now it works perfect :)
