### ISSUE TITLE
Delete User

### ISSUE THREAD

**Issue by ivinkaf** [Hiswe/mosaico-backend#52]
Hi,

how could I please delete user or transfer user from one group to another group?

Thanks

**Comment by Hiswe** [comment]
@ivinkaf users can't be deleted or transferred.
And I have no time to update this BO :/

**Comment by ivinkaf** [comment]
Hi, and is it please possible to delete saved emails? or where in source code could we add something like this?
thanks

**Comment by Hiswe** [comment]
There's only a bulkl remove actions

https://github.com/goodenough/mosaico-backend/blob/master/server/mailings/index.js#L365-L377
