### ISSUE TITLE
I got error when running "npm run dev"

### ISSUE THREAD

**Issue by yudhk** [Hiswe/mosaico-backend#53]
I got this error when running "npm run dev"
[13:16:03] Finished 'rev' after 187 ms
[13:16:03] Starting 'nodemon'...
gulp dev --dev[7577]: ../src/node_contextify.cc:626:static void node::contextify::ContextifyScript::New(const v8::FunctionCallbackInfo<v8::Value>&): Assertion `args[1]->IsString()' failed.
 1: 0x8dc510 node::Abort() [gulp dev --dev]
 2: 0x8dc5e5  [gulp dev --dev]
 3: 0x91081e node::contextify::ContextifyScript::New(v8::FunctionCallbackInfo<v8::Value> const&) [gulp dev --dev]
 4: 0xb6166b  [gulp dev --dev]
 5: 0xb63602 v8::internal::Builtin_HandleApiCall(int, v8::internal::Object**, v8::internal::Isolate*) [gulp dev --dev]
 6: 0x1ded41c5be1d
Aborted
npm ERR! code ELIFECYCLE
npm ERR! errno 134
npm ERR! mosaico@0.17.4 dev: `gulp dev --dev`
npm ERR! Exit status 134
npm ERR!
npm ERR! Failed at the mosaico@0.17.4 dev script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2019-03-24T13_16_03_634Z-debug.log

**Comment by Hiswe** [comment]
It seems to be a problem with Node.
Which version are you using and on which OS?

**Comment by yudhk** [comment]
I have solved the problem by installing the natives and downgrading the node js version from 10.x to 8.x
